[package]
name = "casdoor-rust-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casdoor-rust-sdk = "1.2.1"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.138"